### PR TITLE
Implement signature validation

### PR DESCRIPTION
**Pull request by davispuh**
This PR implements signature validation for both VehicleUnit data and DriverCard data files.

By default signature validation is off, to enable validation, need to set `Validator.ValidateSignatures = true;`

PR depends on #40 and so I've included those commits here.

### CODE REVIEW

**Comment by jugglingcats** [comment]
Great work (including the other PRs)! Feel free to merge as I probably won't get a chance to review it all.

Perhaps you'd also like to update the readme with the new validator info. 

Am aware the readme is quite "informal" at the moment. Perhaps now is a good time to clean it up so it looks less like a toy project?

**Comment by davispuh** [comment]
Note that for validation ASN.1 parser is needed. 
Microsoft's `System.Security.Cryptography.Asn1.Experimental` package is used.

It's published on `dotnet-corefxlab` repository
https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Security.Cryptography.Asn1.Experimental

NuGet source can be added with
```bash
$ nuget sources Add -Name "dotnet-corefxlab" -Source "https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json"
```

**Comment by davispuh** [comment]
> Perhaps you'd also like to update the readme with the new validator info.

Yeah, I'll add that.


> Am aware the readme is quite "informal" at the moment. Perhaps now is a good time to clean it up so it looks less like a toy project?

I'm not exactly sure how to improve that, I think you should fix it up as you wish.

**Comment by jugglingcats** [comment]
No problem! Perhaps you could add an example how to process a file without the intermediate xml, then I'll look at changing the general tone of the readme.

**Comment by davispuh** [comment]
Updated README about signature validation.
I think this PR is complete now.

**Pull request merged**
