### PR TITLE
.Net5.0 upgrade

### PR DESCRIPTION
**Pull request by rimutaka**
`System.Security.Cryptography.Asn1` library is no longer available and its functionality was absorbed into _.Net5.0_, which is nearing its production release, so upgrading straight to 5.0 seems like a logical step. 

### Changes:

1. replaced _.net2.1_ with _.net5.0_
2. updated _.vscode_ files to reflect the change and updated paths to launch from the root folder of the solution
3. upgraded .sln with the latest _Visual Studio_ to allow _.net5.0_ support
4. updated  `README.md` to reflect the changes
5. unrelated to _.net5.0_, added saving _.xml_ files with auto-naming in _no-args_ mode. It was kind of pointless looping through the input files and never seeing any results.

I totally understand if you prefer to keep it at the current .net version. We'll keep developing in our fork under .net5.0 (came across lots of bugs) and can always pull into your repo later.

Thanks so much for sharing the code!

### CODE REVIEW

**Comment by jugglingcats** [comment]
Hi @rimutaka, appreciate you taking the time to put together this pull request. I'm unsure whether to merge because I don't use this project any more and am not up-to-date with .NET changes. I can't judge how this will impact other users of the code. @davispuh do you have a view on this?

**Comment by rimutaka** [comment]
@jugglingcats, no worries. I totally understand. We are actively working on this project. Maybe leave the PR open for now for others to see the work in progress.

**Comment by davispuh** [comment]
Actually I'm pretty much in same boat. I'm not working anymore at the company who's using this in production. But I can say that it's been working very well there (24/7) for a while with way over 100k+ .ddd files processed.

So anyway about this PR, it looks fine but I'm also not really familiar with .NET 5.0 so I would say it's fine to merge as long as it still works with .NET Core.


> We are actively working on this project

That's great, keep PRs coming as looks like whoever is using this will need to submit fixes :P

**Comment by davispuh** [comment]
So I just read this
> .NET 5 is actually dotnet core 4.0, but because Microsoft want to try and simplify the versioning, they have chosen to drop the "core" name for all future versions, and follow on from where 4.8 (The last of the classic framework versions) left off.

So basically by definition it should work :D

**Comment by rimutaka** [comment]
Let the master say on the older version of .NET for now. I pushed these changes to a new branch instead. https://github.com/jugglingcats/tachograph-reader/tree/net5. Further developments will be based on that branch, but if anyone wants to continue with the older .net version they can stay on master. We can merge `net5` into `master` later.

**Pull request closed without merging**
