### PR TITLE
Prevent errors due to non-ascii characters

### PR DESCRIPTION
**Pull request by luisesn**
Prevent errors due to non-ascii characters

### CODE REVIEW

**Comment by jugglingcats** [comment]
Hi @luisesn, my first pull request on this project - thanks!

I'm curious what issue you were hitting. You can see we write using the default encoding... I can't remember off hand what encoding is in the binary driver/vehicle file, or if it specifies the encoding. It seems a bit drastic to simply remove non-ascii characters. This cause issues for users with accented characters, etc?

Right now am not sure I would merge the request, without some more info/context.

**Comment by andreasringdal** [comment]
I had a similar problem where low number ascii characters appeared in the registrationnumber field of some vehicles. (But I do not remember how we solved it.

**Comment by luisesn** [comment]
Exactly, on at least two files (the only two I've tried so far) the vehicleRegistrationNumber field started with an 0x01 character -> [vehicleRegistrationNumber] => 0x01+8377JCD
I wasn't the only field with the problem.
I can provide the files if you want.

**Comment by jugglingcats** [comment]
Would appreciate if you can post the files here: https://drive.google.com/folderview?id=0B9DQIhlN3usON3BMOF9XeWp3UUE&usp=sharing and let me know when done. I'll grab and delete them soon after. Thanks

**Comment by luisesn** [comment]
I have just found at least one of the problems:
The first byte of the VehicleRegistrationNumber is the codePage from the  ISO/IEC 8859 so 0x01 there is correct but should not be read

**Comment by luisesn** [comment]
Doing a "google translation" from  my pdf:

2,114. Vehicle Registration Number
Vehicle registration number (EN). The registration number is assigned by the registration authority
vehicles.
VehicleRegistrationNumber :: = SEQUENCE {
codePage INTEGER (0..255)
vehicleRegistrationNumber OCTET STRING (SIZE (13))
}
codePage specifies the part of the ISO / IEC 8859 used to code the vehicleRegNumber,
vehicleRegNumber is a VRN coded in accordance with ISO / IEC 8859-codePage standard.
Value assignment: country specific.



Anyway I have uploaded the example file.

**Comment by jugglingcats** [comment]
Interesting... that method in SimpleStringRegion should not even be executed. The vehicle registration should be handled by InternationalString which is derived from CodePageStringRegion (https://github.com/jugglingcats/tachograph-reader/blob/master/DataFile.cs#L430).

This is configured in the driver card config here: https://github.com/jugglingcats/tachograph-reader/blob/master/DataFile.cs#L430.

... and in the vehicle unit card here: https://github.com/jugglingcats/tachograph-reader/blob/master/DataFile.cs#L430.

But there are other places in the VU card where registration numbers appear and these do not appear to be correctly coded in the config right now...

In TransferDataActivities here: https://github.com/jugglingcats/tachograph-reader/blob/master/DataFile.cs#L430.

and CalibrationRecords here: https://github.com/jugglingcats/tachograph-reader/blob/master/DataFile.cs#L430.

Can you confirm the type of files you are processing and also whether the issue is in one of the VU areas mentioned (TransferDataActivities or CalibrationRecords)?

Perhaps the correct fix is in the config (data mapping) rather than the code.

Alfie.

**Comment by luisesn** [comment]
Yeah, that is what I was saying in the last messages, I now think what is wrong is the config file, we should add new fields to correctly get the first bytes where needed.

Sorry for the "in-correct correction"

Shall I close this pull? I'm a newbie in github :/

**Comment by jugglingcats** [comment]
I think this pull should be closed. If you are comfortable providing another pull request for the config change that would be great ;)

**Comment by jugglingcats** [comment]
I'm going to close this now based on the above discussion. Pull request for proposed solution always welcome.

**Pull request closed without merging**
